"""Playbook curator agent: reads all trade history and reflections, extracts
recurring strategy patterns with win/loss statistics, and writes a structured
playbook.md that the trading agent reads every cycle as institutional memory."""
import json
import logging
import re
from datetime import datetime
from pathlib import Path

import config
from agent import call_ollama, read_recent_entries

logger = logging.getLogger(__name__)

PLAYBOOK_SYSTEM = """You are a quantitative trading strategy curator for a paper ETF trading agent.
Your job is to analyse a complete trade history and reflections log, identify recurring strategy
patterns that have produced measurable outcomes, and document them in a structured playbook.

Each playbook entry must be grounded in actual trade data — not theory.  You must:
1. Identify the market conditions under which the trade was entered (regime, VIX level, sector context).
2. Describe the specific entry trigger (indicator alignment, event, divergence signal, etc.).
3. Report the empirical outcome across all matching instances: win count, loss count, average P&L %.
4. Identify edge cases and failure modes — when does the pattern fail?
5. Recommend specific adjustments to improve future execution.

Be concrete and data-driven.  Do not invent patterns not supported by the trade data.
Do not include patterns with fewer than 3 instances as they lack statistical significance.
Flag patterns where the sample is still small (3–6 trades) with "LOW SAMPLE — treat as hypothesis."
"""

_PLAYBOOK_HEADER = """# Strategy Playbook

This playbook is auto-generated by the Playbook Curator agent from empirical trade history.
It is updated weekly (Friday pre-market) and read by the trading agent every cycle.
**Do not manually edit this file** — changes will be overwritten on the next update.

Use this playbook as guidance, not as rigid rules.  Context always overrides pattern matching.
High-confidence patterns (65%+ win rate, 8+ trades) warrant lower risk/temperature.
Novel or untested conditions warrant more exploratory thinking.

---
"""


def _parse_trades_for_playbook() -> list[dict]:
    """Parse trade_log.md into structured records for pattern analysis.

    Extracts: date, action, ticker, quantity, price, realized_pnl, reasoning,
    hypothesis (if present), strategy classification.
    """
    from strategy_tracker import classify_trade_strategy

    try:
        with open(config.TRADE_LOG_PATH, "r") as f:
            content = f.read()
    except FileNotFoundError:
        return []

    entries = []
    sections = content.split("\n---\n")

    for section in sections:
        if not section.strip():
            continue
        entry: dict = {}

        # Action and ticker from header line
        header_match = re.search(r"^## (BUY|SELL|NO[_ ]ACTION)[^\n]*", section, re.MULTILINE)
        if not header_match:
            continue
        entry["action"] = header_match.group(1).replace(" ", "_")

        date_match = re.search(r"\*\*Date:\*\*\s*(.+)", section)
        entry["date"] = date_match.group(1).strip() if date_match else ""

        ticker_match = re.search(r"\*\*Instrument:\*\*\s*(\w+)", section)
        entry["ticker"] = ticker_match.group(1).strip() if ticker_match else ""

        price_match = re.search(r"\*\*Price:\*\*\s*\$([\d.]+)", section)
        entry["price"] = float(price_match.group(1)) if price_match else 0.0

        qty_match = re.search(r"\*\*Quantity:\*\*\s*(\d+)", section)
        entry["quantity"] = int(qty_match.group(1)) if qty_match else 0

        pnl_match = re.search(r"\*\*Realized P&L:\*\*\s*\$([-\d.]+)", section)
        entry["realized_pnl"] = float(pnl_match.group(1)) if pnl_match else None

        reasoning_match = re.search(r"\*\*Reasoning:\*\*\s*(.+?)(?=\n- \*\*|\Z)", section, re.DOTALL)
        entry["reasoning"] = reasoning_match.group(1).strip() if reasoning_match else ""

        hyp_match = re.search(r"\*\*Hypothesis:\*\*\s*(.+?)(?=\n- \*\*|\Z)", section, re.DOTALL)
        entry["hypothesis"] = hyp_match.group(1).strip() if hyp_match else ""

        scores_match = re.search(r"\*\*Entry Scores:\*\*\s*(\{.+?\})", section)
        if scores_match:
            try:
                entry["entry_scores"] = json.loads(scores_match.group(1))
            except json.JSONDecodeError:
                entry["entry_scores"] = {}

        entry["strategy"] = classify_trade_strategy(entry["reasoning"])
        entries.append(entry)

    return entries


def _build_pattern_summary(trades: list[dict]) -> str:
    """Build a compact text summary of trades grouped by strategy and ticker
    to feed into the LLM for pattern extraction."""
    from collections import defaultdict
    from strategy_tracker import STRATEGY_DEFINITIONS

    # Group closed trades (SELL with realized_pnl) by strategy
    closed: list[dict] = [t for t in trades if t["action"] == "SELL" and t.get("realized_pnl") is not None]

    if not closed:
        return "No closed trades available for pattern analysis."

    by_strategy: dict[str, list[dict]] = defaultdict(list)
    for t in closed:
        by_strategy[t["strategy"]].append(t)

    lines = [f"Total closed trades: {len(closed)}\n"]
    lines.append("=" * 60)

    for strategy, group in sorted(by_strategy.items(), key=lambda x: -len(x[1])):
        if len(group) < 2:
            continue
        wins = sum(1 for t in group if t.get("realized_pnl", 0) > 0.01)
        losses = sum(1 for t in group if t.get("realized_pnl", 0) < -0.01)
        neutral = len(group) - wins - losses
        total_pnl = sum(t.get("realized_pnl", 0) for t in group)
        win_rate = wins / len(group) if group else 0
        display = STRATEGY_DEFINITIONS.get(strategy, {}).get("display", strategy)

        lines.append(f"\n### {display} ({len(group)} trades | {wins}W/{losses}L | {win_rate*100:.0f}% | P&L ${total_pnl:+.2f})")

        for t in group[-10:]:  # show last 10 examples
            pnl = t.get("realized_pnl", 0)
            sign = "✓" if pnl > 0.01 else ("✗" if pnl < -0.01 else "—")
            hyp = f" | Hyp: {t['hypothesis'][:80]}" if t.get("hypothesis") else ""
            lines.append(
                f"  {sign} {t['date'][:10]} {t['ticker']} @ ${t['price']}"
                f" P&L: ${pnl:+.2f}{hyp}"
            )
            if t.get("reasoning"):
                lines.append(f"     Reasoning: {t['reasoning'][:120]}...")

    return "\n".join(lines)


def run_playbook_update() -> str:
    """Analyse all trade history and reflections, then write an updated playbook.md.

    This is the main entry point called by the scheduler and API.
    """
    logger.info("Starting playbook update...")

    trades = _parse_trades_for_playbook()
    if not trades:
        logger.warning("No trades found — skipping playbook update")
        return "No trade history available for playbook generation."

    pattern_summary = _build_pattern_summary(trades)

    # Also include recent reflections for qualitative patterns
    reflections = read_recent_entries(config.REFLECTIONS_PATH, 20)

    now = datetime.now()
    prompt = f"""You are analysing a complete trading history to build a structured strategy playbook.

Date: {now.strftime('%Y-%m-%d')}
Total trades in history: {len(trades)}

## Trade History by Strategy
{pattern_summary}

## Recent Reflections (last 20 entries)
{reflections[:3000]}

---

Generate a structured strategy playbook.  For each strategy pattern that has 3+ instances:

**Format each entry exactly like this:**

## Pattern: [Descriptive Name]
**Strategy Type:** [Category]
**Conditions:** [Market conditions: regime, VIX, sector context, instrument type]
**Entry Trigger:** [Specific technical/fundamental signal that initiates the trade]
**Outcomes:** [N instances | X wins | Y losses | Z neutral | Win rate: %% | Avg P&L: %%]
**Edge:** [Why this pattern has an edge — what fundamental or technical mechanism drives it]
**Failure Modes:** [When does this pattern fail? Common mistakes?]
**Execution Notes:** [Specific sizing, timing, or exit guidance based on outcomes]
**Confidence:** [HIGH (65%%+ win rate, 8+ trades) | MEDIUM (50-65%% or 4-7 trades) | LOW SAMPLE (3 trades)]

---

After all patterns, add a final section:

## Strategies to Avoid
List any strategies that have poor empirical results and should be actively avoided or treated
with extreme caution.  Include specific conditions under which even normally-good strategies fail.

## Untested Hypotheses
List 2-3 pattern hypotheses that show early promise but lack sufficient data.
Label them clearly as hypotheses, not validated patterns.

Be specific.  Reference actual tickers, dates, and P&L numbers from the data above.
Do not include patterns with fewer than 3 instances."""

    resolved_model = config.PLAYBOOK_MODEL or config.RESEARCH_MODEL
    response = call_ollama(
        prompt,
        system=PLAYBOOK_SYSTEM,
        model=resolved_model,
        timeout=config.PLAYBOOK_TIMEOUT,
    )

    if response.startswith("[ERROR]"):
        logger.error(f"Playbook LLM call failed: {response}")
        return response

    timestamp = now.strftime("%Y-%m-%d %H:%M:%S")
    content = (
        _PLAYBOOK_HEADER
        + f"*Last updated: {timestamp} | Trades analysed: {len(trades)}*\n\n---\n\n"
        + response
    )

    with open(config.PLAYBOOK_PATH, "w") as f:
        f.write(content)

    logger.info(f"Playbook updated at {config.PLAYBOOK_PATH} ({len(response)} chars)")
    return response


def get_playbook_context(max_chars: int = 3000) -> str:
    """Read playbook.md and return the most relevant sections for the trading prompt.

    Truncates to max_chars to avoid overwhelming the context window.
    """
    try:
        with open(config.PLAYBOOK_PATH, "r") as f:
            content = f.read()
    except FileNotFoundError:
        return "No strategy playbook available yet. Will be generated after sufficient trade history accumulates."

    # Strip the header boilerplate, keep the patterns
    lines = content.split("\n")
    start_idx = 0
    for i, line in enumerate(lines):
        if line.startswith("## Pattern:") or line.startswith("## Strategies"):
            start_idx = i
            break

    relevant = "\n".join(lines[start_idx:])
    if len(relevant) > max_chars:
        relevant = relevant[:max_chars] + "\n\n[...playbook truncated — see playbook.md for full content]"

    return relevant


def get_adaptive_temperature() -> float:
    """Compute an adaptive temperature for the trading agent based on playbook confidence.

    - High-confidence patterns available (≥PLAYBOOK_HIGH_CONFIDENCE_WIN_RATE win rate,
      ≥PLAYBOOK_HIGH_CONFIDENCE_MIN_TRADES samples) → TEMPERATURE_HIGH_CONFIDENCE (exploit)
    - Some patterns but low confidence → config.TEMPERATURE (default)
    - No applicable patterns → TEMPERATURE_NO_PATTERN (explore)
    """
    try:
        from strategy_tracker import _load_scores
        scores = _load_scores()
    except Exception:
        return config.TEMPERATURE

    min_trades = config.PLAYBOOK_HIGH_CONFIDENCE_MIN_TRADES
    min_win_rate = config.PLAYBOOK_HIGH_CONFIDENCE_WIN_RATE

    has_any_patterns = False
    has_high_confidence = False

    for entry in scores.values():
        total = entry.get("total", 0)
        win_rate = entry.get("win_rate")
        if total == 0 or entry.get("suspended", False):
            continue
        has_any_patterns = True
        if total >= min_trades and win_rate is not None and win_rate >= min_win_rate:
            has_high_confidence = True
            break

    if has_high_confidence:
        return config.TEMPERATURE_HIGH_CONFIDENCE
    elif has_any_patterns:
        return config.TEMPERATURE   # default — some history, mixed confidence
    else:
        return config.TEMPERATURE_NO_PATTERN   # no history → explore more freely
